mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082
spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: JtE75WpELXL8dyKs
    url: jdbc:mysql://42.192.209.81:3306/vue_mys?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: vue_mys